version: "3.7"

services:

  spark-master:
    image: jarzamendia/spark-master:latest
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      spark-network:
    environment:
      - INIT_DAEMON_STEP=setup_spark

  spark-worker:
    image: jarzamendia/spark-worker:latest
    ports:
      - "8081:8081"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_LOCAL_IP=0.0.0.0
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=128m
      - SPARK_EXECUTOR_MEMORY=256m
    deploy:
      mode: replicated
      replicas: 2
    networks: 
      spark-network:

networks:
  spark-network:
    driver: overlay