FROM jarzamendia/oracle-jre:latest

ENV SPARK_HOME="/opt/spark"
ENV PATH="$PATH:$SPARK_HOME/bin:$SPARK_HOME/sbin"
ENV ENABLE_INIT_DAEMON true
ENV INIT_DAEMON_BASE_URI http://identifier/init-daemon
ENV INIT_DAEMON_STEP spark_master_init
ENV PYTHONHASHSEED 1

EXPOSE 18080 8080 8081 7077 6066 4040

WORKDIR "$SPARK_HOME"

RUN curl -Ls "http://ftp.unicamp.br/pub/apache/spark/spark-2.4.4/spark-2.4.4-bin-hadoop2.7.tgz" | tar zxvf - -C "$SPARK_HOME" --strip=1

RUN apk add --no-cache python3 && \
  curl https://bootstrap.pypa.io/get-pip.py | python3 && \
  ln -sv /usr/bin/python3 /usr/bin/python  # Only support python3 to reduce image size

COPY wait-for-step.sh /
COPY execute-step.sh /
COPY finish-step.sh /

#Give permission to execute scripts
RUN chmod +x /wait-for-step.sh && chmod +x /execute-step.sh && chmod +x /finish-step.sh

CMD ["spark-class", "org.apache.spark.deploy.master.Master"]