version: 2.1

executors:

  docker-publisher:
    environment:
      IMAGE_NAME: jarzamendia/spark
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:

  build-v2:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image Base
          command: |
            docker build -t $IMAGE_NAME-base:latest -f v2/Dockerfile-base .
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            IMAGE_TAG=spark2.4.7-hadoop2.7
            docker tag $IMAGE_NAME-base:latest $IMAGE_NAME-base:$IMAGE_TAG
            docker push $IMAGE_NAME-base:latest
            docker push $IMAGE_NAME-base:$IMAGE_TAG

      - run:
          name: Build Docker image Master
          command: |
            docker build -t $IMAGE_NAME-master:latest -f v2/Dockerfile-master .
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            IMAGE_TAG=spark2.4.7-hadoop2.7
            docker tag $IMAGE_NAME-master:latest $IMAGE_NAME-master:$IMAGE_TAG
            docker push $IMAGE_NAME-master:latest
            docker push $IMAGE_NAME-master:$IMAGE_TAG

      - run:
          name: Build Docker image Worker
          command: |
            docker build -t $IMAGE_NAME-worker:latest -f v2/Dockerfile-worker .
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            IMAGE_TAG=spark2.4.7-hadoop2.7
            docker tag $IMAGE_NAME-worker:latest $IMAGE_NAME-worker:$IMAGE_TAG
            docker push $IMAGE_NAME-worker:latest
            docker push $IMAGE_NAME-worker:$IMAGE_TAG

  build-v3:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image Base
          command: |
            IMAGE_TAG=spark3.1.2-hadoop3.2
            docker build -t $IMAGE_NAME-base:$IMAGE_TAG -f v3/Dockerfile-base .
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME-base:$IMAGE_TAG

      - run:
          name: Build Docker image Master
          command: |
            IMAGE_TAG=spark3.1.2-hadoop3.2
            docker build -t $IMAGE_NAME-master:$IMAGE_TAG -f v3/Dockerfile-master .
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME-master:$IMAGE_TAG

      - run:
          name: Build Docker image Worker
          command: |
            IMAGE_TAG=spark3.1.2-hadoop3.2
            docker build -t $IMAGE_NAME-worker:$IMAGE_TAG -f v3/Dockerfile-worker .
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME-worker:$IMAGE_TAG

workflows:

  version: 2

  build-master:
    jobs:
      - build-v2:
          filters:
            branches:
              only: master

      - build-v3:
          filters:
            branches:
              only: master